services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  edge-service:
    build:
      context: ./edge-service
    ports:
      - "8090:8090"
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  customer-service:
    build:
      context: ./customer-service
    ports:
      - "8091:8091"
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  inventory-service:
    build:
      context: ./inventory-service
    ports:
      - "8092:8092"
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8093:8093"
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  order-service:
    build:
      context: ./order-service
    ports:
      - "8094:8094"
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker
